// Shared TypeScript types + presentation helpers for the chunk #88
// Diagnostic Report surface. Mirrors the Rust `ReportPayload` struct
// at `pulse-app/src/incidents_router.rs`; canonical bindings live in
// `pulse-app/ui/src/bindings/index.ts` (auto-generated by taurpc +
// specta). Local re-exports provide а stable consumer surface for the
// Report.tsx + ReportRenderer.tsx + use-report.ts modules without
// repeatedly importing through `../bindings/index`.
//
// Note: TS bindings rename `triage::contract::Severity` к `IncidentSeverity`
// to avoid conflict with `ingest::connection::Severity` (per bindings.ts
// line 76 comment). This file uses `IncidentSeverity` throughout per the
// canonical bindings shape.

import type {
  HypothesisPayload,
  IncidentSeverity,
  IncidentStatus,
  InvestigationStepPayload,
  PreviouslySeenPayload,
  ReportPayload,
} from "../bindings/index";

export type {
  HypothesisPayload,
  IncidentSeverity,
  IncidentStatus,
  InvestigationStepPayload,
  PreviouslySeenPayload,
  ReportPayload,
};

/// Bounded copy-state machine за the copy-markdown action. Drives the
/// non-suppressible visible event per CLAUDE.md §Critical Warnings
/// snapshot/clipboard hygiene rule + a11y status-message contract
/// (`<div role="status" aria-live="polite">`).
export type CopyState = "idle" | "copying" | "copied" | "error";

/// Human-readable status banner copy. Stable strings — а11y screen-reader
/// announcements consume these verbatim.
export function statusLabel(status: IncidentStatus): string {
  switch (status) {
    case "active":
      return "Active";
    case "acknowledged":
      return "Acknowledged";
    case "resolved":
      return "Resolved";
  }
}

/// Human-readable severity badge text.
export function severityLabel(severity: IncidentSeverity): string {
  switch (severity) {
    case "info":
      return "Info";
    case "warn":
      return "Warn";
    case "error":
      return "Error";
    case "critical":
      return "Critical";
  }
}

/// Tailwind-v4 token reference for severity badge backgrounds. Pairs
/// MUST be tested against а11y plan §6 Color contrast pairs ≥ 4.5:1 for
/// text + ≥ 3:1 для non-text. Verified via colorjs.io harness at chunk
/// #12 + design-token contrast tests.
export function severityBackgroundVar(severity: IncidentSeverity): string {
  switch (severity) {
    case "info":
      return "var(--color-raised-2)";
    case "warn":
      return "var(--color-raised-1)";
    case "error":
      return "var(--color-raised-1)";
    case "critical":
      return "var(--color-raised-1)";
  }
}

// Chunk #99 re-audit finding: accent #C7556A is a NON-TEXT token (3.0:1
// SC 1.4.11 classification per design-system Decisions Log 2026-05-03) —
// using it as 12px label TEXT measured 3.37:1 on raised-1
// (color-contrast@serious). Severity hue moves to the badge BORDER
// (non-text, 3:1 applies); the label text stays text-primary and conveys
// severity as a word (SC 1.4.1 not-color-alone).
export function severityTextColorVar(severity: IncidentSeverity): string {
  switch (severity) {
    case "info":
    case "warn":
    case "error":
    case "critical":
      return "var(--color-text-primary)";
  }
}

export function severityBorderColorVar(severity: IncidentSeverity): string {
  switch (severity) {
    case "info":
      return "var(--color-primary)";
    case "warn":
      return "var(--color-text-secondary)";
    case "error":
      return "var(--color-accent)";
    case "critical":
      return "var(--color-accent)";
  }
}

/// Format а unix-nanosecond timestamp as а compact ISO-like string
/// suitable для the Report metadata block. Deterministic; never throws.
/// Used by ReportRenderer для the "Opened" metadata row.
export function formatOpenedAt(unixNano: number): string {
  if (!Number.isFinite(unixNano) || unixNano <= 0) {
    return "—";
  }
  const ms = Math.floor(unixNano / 1_000_000);
  try {
    return new Date(ms).toISOString();
  } catch {
    return "—";
  }
}

/// Default copy-state message strings for the Modal's live region.
/// Stable strings — screen reader announces verbatim per а11y plan §7.
export const COPY_LIVE_REGION_MESSAGES: Readonly<Record<CopyState, string>> = {
  idle: "",
  copying: "Copying report to clipboard…",
  copied: "Report copied to clipboard.",
  error: "Failed to copy report to clipboard.",
};

/// Number of section markers expected in а serialized markdown payload
/// (six sections per P-031 + optional Resolution Summary + optional
/// Previously Seen). Tests grep for these markers to verify rendering.
export const REPORT_SECTION_HEADINGS = [
  "## Symptom",
  "## Timeline",
  "## Hypotheses",
  "## Investigation Steps",
  "## Evidence",
  "## Project Context",
] as const;
