export const PAIRS = [
  {
    pair_name: "text-primary/base",
    fg_token: "--color-text-primary",
    bg_token: "--color-base",
    target_ratio: 4.5,
    wcag_criterion: "SC 1.4.3",
    wcag_level: "AA",
    usage: "normal-text",
    severity: "critical",
  },
  {
    pair_name: "text-secondary/base",
    fg_token: "--color-text-secondary",
    bg_token: "--color-base",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.3",
    wcag_level: "AA",
    usage: "large-text-only",
    severity: "critical",
  },
  {
    pair_name: "text-tertiary/base",
    fg_token: "--color-text-tertiary",
    bg_token: "--color-base",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.3",
    wcag_level: "AA",
    usage: "large-text-only",
    severity: "critical",
  },
  {
    pair_name: "primary/base",
    fg_token: "--color-primary",
    bg_token: "--color-base",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "non-text",
    severity: "critical",
  },
  {
    pair_name: "feedback-success/inset",
    fg_token: "--color-feedback-success",
    bg_token: "--color-inset",
    target_ratio: 4.5,
    wcag_criterion: "SC 1.4.3",
    wcag_level: "AA",
    usage: "normal-text-or-non-text",
    severity: "critical",
  },
  {
    pair_name: "accent/base",
    fg_token: "--color-accent",
    bg_token: "--color-base",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "non-text",
    severity: "critical",
  },
  {
    pair_name: "border-focus/base",
    fg_token: "--border-focus",
    bg_token: "--color-base",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "focus-ring",
    severity: "critical",
  },
  {
    pair_name: "border-focus/raised-1",
    fg_token: "--border-focus",
    bg_token: "--color-raised-1",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "focus-ring-on-surface-variant",
    severity: "informational",
  },
  {
    pair_name: "border-focus/raised-2",
    fg_token: "--border-focus",
    bg_token: "--color-raised-2",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "focus-ring-on-surface-variant",
    severity: "informational",
  },
  {
    pair_name: "border-focus/raised-3",
    fg_token: "--border-focus",
    bg_token: "--color-raised-3",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "focus-ring-on-surface-variant",
    severity: "informational",
  },
  {
    pair_name: "border-focus/inset",
    fg_token: "--border-focus",
    bg_token: "--color-inset",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.11",
    wcag_level: "AA",
    usage: "focus-ring-on-surface-variant",
    severity: "informational",
  },
  {
    pair_name: "text-muted/base",
    fg_token: "--color-text-muted",
    bg_token: "--color-base",
    target_ratio: 3.0,
    wcag_criterion: "SC 1.4.3",
    wcag_level: "AA",
    usage: "decorative-only",
    severity: "informational",
  },
];
