use std::net::SocketAddr;
use std::sync::Arc;

use tonic::transport::Server;
use tonic::{Request, Response, Status};

use crate::channel::{Batch, IngestSender};
use crate::contract::Error;
use crate::invariants::{
    validate_resource_logs, validate_resource_metrics, validate_resource_spans,
};
use crate::state::IngestState;

pub const MAX_DECODING_MESSAGE_SIZE: usize = 8 * 1024 * 1024;
pub const DEFAULT_GRPC_PORT: u16 = 4317;

// Vendored OTLP proto stubs generated by tonic-prost-build (see build.rs).
// Module nesting mirrors proto package hierarchy `opentelemetry.proto.X.vN`
// so cross-import super:: refs in generated code resolve correctly.
#[allow(clippy::all, missing_docs)]
pub mod proto {
    pub mod opentelemetry {
        pub mod proto {
            pub mod common {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.common.v1");
                }
            }
            pub mod resource {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.resource.v1");
                }
            }
            pub mod trace {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.trace.v1");
                }
            }
            pub mod metrics {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.metrics.v1");
                }
            }
            pub mod logs {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.logs.v1");
                }
            }
            pub mod collector {
                pub mod trace {
                    pub mod v1 {
                        tonic::include_proto!("opentelemetry.proto.collector.trace.v1");
                    }
                }
                pub mod metrics {
                    pub mod v1 {
                        tonic::include_proto!("opentelemetry.proto.collector.metrics.v1");
                    }
                }
                pub mod logs {
                    pub mod v1 {
                        tonic::include_proto!("opentelemetry.proto.collector.logs.v1");
                    }
                }
            }
        }
    }
}

use proto::opentelemetry::proto::collector::logs::v1::logs_service_server::{
    LogsService, LogsServiceServer,
};
use proto::opentelemetry::proto::collector::logs::v1::{
    ExportLogsServiceRequest, ExportLogsServiceResponse,
};
use proto::opentelemetry::proto::collector::metrics::v1::metrics_service_server::{
    MetricsService, MetricsServiceServer,
};
use proto::opentelemetry::proto::collector::metrics::v1::{
    ExportMetricsServiceRequest, ExportMetricsServiceResponse,
};
use proto::opentelemetry::proto::collector::trace::v1::trace_service_server::{
    TraceService, TraceServiceServer,
};
use proto::opentelemetry::proto::collector::trace::v1::{
    ExportTraceServiceRequest, ExportTraceServiceResponse,
};

#[derive(Clone)]
struct TraceServiceImpl {
    state: Arc<IngestState>,
    sender: Arc<IngestSender>,
}

#[derive(Clone)]
struct MetricsServiceImpl {
    state: Arc<IngestState>,
    sender: Arc<IngestSender>,
}

#[derive(Clone)]
struct LogsServiceImpl {
    state: Arc<IngestState>,
    sender: Arc<IngestSender>,
}

#[tonic::async_trait]
impl TraceService for TraceServiceImpl {
    #[tracing::instrument(
        skip(self, req),
        fields(
            rpc.system = "grpc",
            rpc.service = "TraceService",
            rpc.method = "Export",
            span_count = tracing::field::Empty,
            traceparent = tracing::field::Empty,
        ),
    )]
    async fn export(
        &self,
        req: Request<ExportTraceServiceRequest>,
    ) -> Result<Response<ExportTraceServiceResponse>, Status> {
        if let Some(tp) = extract_traceparent(req.metadata()) {
            tracing::Span::current().record("traceparent", tracing::field::display(&tp));
        }
        let payload = req.into_inner();
        let span_count = {
            let _decode_span = tracing::debug_span!("parse.protobuf").entered();
            count_spans(&payload)
        };
        tracing::Span::current().record("span_count", span_count);
        if let Err(e) = validate_resource_spans(&payload.resource_spans) {
            return Err(reject_invariant(e));
        }
        if let Err(e) = self.sender.try_send(Batch::Spans(payload.resource_spans)) {
            return Err(reject_channel(e));
        }
        self.state.record_spans(span_count);
        Ok(Response::new(ExportTraceServiceResponse::default()))
    }
}

#[tonic::async_trait]
impl MetricsService for MetricsServiceImpl {
    #[tracing::instrument(
        skip(self, req),
        fields(
            rpc.system = "grpc",
            rpc.service = "MetricsService",
            rpc.method = "Export",
            span_count = tracing::field::Empty,
            traceparent = tracing::field::Empty,
        ),
    )]
    async fn export(
        &self,
        req: Request<ExportMetricsServiceRequest>,
    ) -> Result<Response<ExportMetricsServiceResponse>, Status> {
        if let Some(tp) = extract_traceparent(req.metadata()) {
            tracing::Span::current().record("traceparent", tracing::field::display(&tp));
        }
        let payload = req.into_inner();
        let dp_count = {
            let _decode_span = tracing::debug_span!("parse.protobuf").entered();
            count_metric_data_points(&payload)
        };
        tracing::Span::current().record("span_count", dp_count);
        if let Err(e) = validate_resource_metrics(&payload.resource_metrics) {
            return Err(reject_invariant(e));
        }
        if let Err(e) = self
            .sender
            .try_send(Batch::Metrics(payload.resource_metrics))
        {
            return Err(reject_channel(e));
        }
        self.state.record_metric_data_points(dp_count);
        Ok(Response::new(ExportMetricsServiceResponse::default()))
    }
}

#[tonic::async_trait]
impl LogsService for LogsServiceImpl {
    #[tracing::instrument(
        skip(self, req),
        fields(
            rpc.system = "grpc",
            rpc.service = "LogsService",
            rpc.method = "Export",
            span_count = tracing::field::Empty,
            traceparent = tracing::field::Empty,
        ),
    )]
    async fn export(
        &self,
        req: Request<ExportLogsServiceRequest>,
    ) -> Result<Response<ExportLogsServiceResponse>, Status> {
        if let Some(tp) = extract_traceparent(req.metadata()) {
            tracing::Span::current().record("traceparent", tracing::field::display(&tp));
        }
        let payload = req.into_inner();
        let log_count = {
            let _decode_span = tracing::debug_span!("parse.protobuf").entered();
            count_log_records(&payload)
        };
        tracing::Span::current().record("span_count", log_count);
        if let Err(e) = validate_resource_logs(&payload.resource_logs) {
            return Err(reject_invariant(e));
        }
        if let Err(e) = self.sender.try_send(Batch::Logs(payload.resource_logs)) {
            return Err(reject_channel(e));
        }
        self.state.record_log_records(log_count);
        Ok(Response::new(ExportLogsServiceResponse::default()))
    }
}

fn count_spans(req: &ExportTraceServiceRequest) -> u64 {
    req.resource_spans
        .iter()
        .map(|rs| {
            rs.scope_spans
                .iter()
                .map(|ss| ss.spans.len() as u64)
                .sum::<u64>()
        })
        .sum()
}

fn count_metric_data_points(req: &ExportMetricsServiceRequest) -> u64 {
    req.resource_metrics
        .iter()
        .map(|rm| {
            rm.scope_metrics
                .iter()
                .map(|sm| sm.metrics.len() as u64)
                .sum::<u64>()
        })
        .sum()
}

fn count_log_records(req: &ExportLogsServiceRequest) -> u64 {
    req.resource_logs
        .iter()
        .map(|rl| {
            rl.scope_logs
                .iter()
                .map(|sl| sl.log_records.len() as u64)
                .sum::<u64>()
        })
        .sum()
}

fn extract_traceparent(metadata: &tonic::metadata::MetadataMap) -> Option<String> {
    let bin = metadata.get_bin("grpc-trace-bin")?;
    let bytes = bin.to_bytes().ok()?;
    Some(
        bytes
            .iter()
            .map(|b| format!("{:02x}", b))
            .collect::<String>(),
    )
}

fn sanitize_error(e: &(impl std::fmt::Display + ?Sized)) -> String {
    // Per security plan §Error Handling: sanitized one-liner; no struct names /
    // file paths / library versions / internal hostnames in user-visible boundary
    // errors. tonic::transport::Error + io::Error display strings are typically
    // safe (e.g., "address in use"), but normalize to the displayed form only.
    format!("{}", e)
}

fn reject_invariant(e: Error) -> Status {
    if let Error::InvariantViolation {
        kind,
        expected,
        actual,
    } = e
    {
        tracing::error!(
            target: "ingest.grpc.parse.error",
            span_field_invalid = kind,
            expected_length = expected as u64,
            actual_length = actual as u64,
            rejection_reason = "post_decode_invariant",
            "OTLP invariant violation",
        );
    }
    Status::invalid_argument("invalid OTLP payload")
}

fn reject_channel(_e: Error) -> Status {
    tracing::warn!(
        target: "ingest.channel.full",
        channel_name = "ingest",
        capacity_pct = 100.0,
        rejection_reason = "saturated",
        "ingest channel saturated",
    );
    Status::resource_exhausted("ingest channel saturated")
}

/// Bind a TCP listener on `addr`. Splitting bind from serve allows callers
/// (e.g., pulse-app/src/main.rs) to record `BindStatus::Ok` to the health
/// envelope as soon as the listener accepts before serve_on enters its
/// long-running future.
pub async fn try_bind(addr: SocketAddr) -> Result<tokio::net::TcpListener, Error> {
    tokio::net::TcpListener::bind(addr)
        .await
        .map_err(|e| Error::BindFailed {
            reason: sanitize_error(&e),
        })
}

/// Serve OTLP gRPC traffic on a previously-bound listener. Returns `Err` only
/// on a fatal serve error (typically the listener closes); never returns
/// `Ok(())` on its own — the future resolves only when the server shuts down.
pub async fn serve_on(
    listener: tokio::net::TcpListener,
    state: Arc<IngestState>,
    sender: Arc<IngestSender>,
) -> Result<(), Error> {
    let trace_svc = TraceServiceImpl {
        state: Arc::clone(&state),
        sender: Arc::clone(&sender),
    };
    let metrics_svc = MetricsServiceImpl {
        state: Arc::clone(&state),
        sender: Arc::clone(&sender),
    };
    let logs_svc = LogsServiceImpl { state, sender };

    let incoming = tokio_stream::wrappers::TcpListenerStream::new(listener);

    Server::builder()
        .add_service(
            TraceServiceServer::new(trace_svc).max_decoding_message_size(MAX_DECODING_MESSAGE_SIZE),
        )
        .add_service(
            MetricsServiceServer::new(metrics_svc)
                .max_decoding_message_size(MAX_DECODING_MESSAGE_SIZE),
        )
        .add_service(
            LogsServiceServer::new(logs_svc).max_decoding_message_size(MAX_DECODING_MESSAGE_SIZE),
        )
        .serve_with_incoming(incoming)
        .await
        .map_err(|e| Error::ServeFailed {
            reason: sanitize_error(&e),
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use proto::opentelemetry::proto::trace::v1::{ResourceSpans, ScopeSpans, Span};

    #[test]
    fn count_spans_sums_across_resource_and_scope() {
        let req = ExportTraceServiceRequest {
            resource_spans: vec![
                ResourceSpans {
                    resource: None,
                    scope_spans: vec![
                        ScopeSpans {
                            scope: None,
                            spans: vec![Span::default(), Span::default()],
                            schema_url: String::new(),
                        },
                        ScopeSpans {
                            scope: None,
                            spans: vec![Span::default()],
                            schema_url: String::new(),
                        },
                    ],
                    schema_url: String::new(),
                },
                ResourceSpans {
                    resource: None,
                    scope_spans: vec![ScopeSpans {
                        scope: None,
                        spans: vec![Span::default()],
                        schema_url: String::new(),
                    }],
                    schema_url: String::new(),
                },
            ],
        };
        assert_eq!(count_spans(&req), 4);
    }

    #[test]
    fn count_spans_zero_for_empty() {
        let req = ExportTraceServiceRequest::default();
        assert_eq!(count_spans(&req), 0);
    }

    #[test]
    fn extract_traceparent_returns_none_when_missing() {
        let metadata = tonic::metadata::MetadataMap::new();
        assert_eq!(extract_traceparent(&metadata), None);
    }

    #[test]
    fn extract_traceparent_returns_hex_when_present() {
        let mut metadata = tonic::metadata::MetadataMap::new();
        let bytes = vec![0xde, 0xad, 0xbe, 0xef];
        metadata.insert_bin(
            "grpc-trace-bin",
            tonic::metadata::MetadataValue::from_bytes(&bytes),
        );
        assert_eq!(extract_traceparent(&metadata), Some("deadbeef".to_string()));
    }

    #[test]
    fn max_decoding_size_is_8_mb() {
        assert_eq!(MAX_DECODING_MESSAGE_SIZE, 8 * 1024 * 1024);
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn try_bind_succeeds_on_ephemeral_port() {
        let addr = SocketAddr::from(([127, 0, 0, 1], 0));
        let listener = try_bind(addr)
            .await
            .expect("bind on ephemeral port must succeed");
        let bound = listener.local_addr().expect("listener has a local addr");
        assert_eq!(bound.ip().to_string(), "127.0.0.1");
        assert_ne!(bound.port(), 0);
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn try_bind_returns_bind_failed_on_collision() {
        let addr = SocketAddr::from(([127, 0, 0, 1], 0));
        let listener_a = try_bind(addr).await.expect("first bind must succeed");
        let bound = listener_a.local_addr().unwrap();
        let result = try_bind(bound).await;
        assert!(matches!(result, Err(Error::BindFailed { .. })));
    }
}
