#!/usr/bin/env bash
# scripts/agent-run.sh — agent-driven verification harness driver
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# 5-command discipline:
#   boot     — pre-build under the boot env, spawn target/release/pulse-app BY PATH,
#              wait for the harness:ready verdict (10s timeout; build absorbed before it);
#              `boot engine` does the same for the console engine,
#              target/release/andromeda-pulse-engine run
#   run      — execute cargo-nextest test suite
#   status   — real-process verdict via cargo xtask harness:status, asked for the
#              window app's run; `status engine` asks for the console engine's
#   cleanup  — terminate the app pid, then verify pid gone + ports released; exit 0
#              only on verified teardown (bounded verdict token on stdout)
#   logs     — tail the structured JSON log file
#
# Bound contracts:
#   - test-plan §3: 5-command discipline, status endpoint shape, PID file path, log format
#   - obs-plan §3: structured log path (~/.andromeda-pulse/logs/agent-latest.jsonl), tracing JSON

set -euo pipefail

# UTF-8 relay: without these, Python helpers invoked from the harness decode
# their own output under the host's legacy codepage and mangle non-ASCII.
export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

# Resolve harness paths (override-friendly via env vars per arch §Occupied Resources)
TMP_BASE="${TMPDIR:-/tmp}"
DATA_DIR="${ANDROMEDA_PULSE_DATA_DIR:-$TMP_BASE/agent-run-$$}"
PIDFILE="${ANDROMEDA_PULSE_PIDFILE:-$DATA_DIR/run/andromeda-pulse.pid}"
LOGFILE="${ANDROMEDA_PULSE_LOGFILE:-$DATA_DIR/logs/agent-latest.jsonl}"
STATUS_TIMEOUT_SEC="${HARNESS_STATUS_TIMEOUT:-10}"
GRPC_PORT="${ANDROMEDA_PULSE_OTLP_GRPC_PORT:-4317}"
HTTP_PORT="${ANDROMEDA_PULSE_OTLP_HTTP_PORT:-4318}"

usage() {
  echo "Usage: $0 {boot [engine]|run|status [engine]|cleanup|logs}" >&2
  echo "" >&2
  echo "  boot, status           the window app (target/release/pulse-app)" >&2
  echo "  boot engine,           the console engine" >&2
  echo "  status engine          (target/release/andromeda-pulse-engine run)" >&2
  echo "" >&2
  echo "Bindings:" >&2
  echo "  test-plan §3 — 5-command discipline, status endpoint, PID file" >&2
  echo "  obs-plan §3  — JSON log file at ~/.andromeda-pulse/logs/agent-latest.jsonl" >&2
  exit 2
}

# The program a verb is asked for: the word after boot or status. No word is
# the window app; `engine` is the console engine. The verdict the verb reads
# is held against the program the run's own log records, so a verb pointed
# at the other program's data dir says wrong-program instead of grading it.
PROGRAM="window"
case "${1:-}" in
  boot|status)
    case "${2:-}" in
      "") ;;
      engine) PROGRAM="console" ;;
      *) usage ;;
    esac
    ;;
esac

mkdir -p "$DATA_DIR/run" "$DATA_DIR/logs"

case "${1:-}" in
  boot)
    # Start the program in background with isolated data dir
    export ANDROMEDA_PULSE_DATA_DIR="$DATA_DIR"
    export ANDROMEDA_PULSE_LOG_LEVEL="${ANDROMEDA_PULSE_LOG_LEVEL:-debug}"
    export RUST_LOG="${RUST_LOG:-debug}"

    APP_NAME="pulse-app"
    WITNESS_LIB=""
    WITNESS_FILE="$DATA_DIR/logs/exit-witness.jsonl"
    if [ "$PROGRAM" = console ]; then
      # The console engine is spawned with no preload whatever the witness
      # variable holds: boot engine never reads it.
      APP_NAME="andromeda-pulse-engine"
    else
      # The exit witness (scripts/exit-witness.c): when the harness names a
      # built library, the app alone is spawned with it loaded. A name that is
      # no regular file ends boot here, so a mistyped path cannot run a job
      # without its witness.
      WITNESS_LIB="${ANDROMEDA_PULSE_EXIT_WITNESS_LIB:-}"
      WITNESS_LIB="${WITNESS_LIB#"${WITNESS_LIB%%[![:space:]]*}"}"
      WITNESS_LIB="${WITNESS_LIB%"${WITNESS_LIB##*[![:space:]]}"}"
      if [ -n "$WITNESS_LIB" ] && [ ! -f "$WITNESS_LIB" ]; then
        echo "boot: exit witness library not found" >&2
        exit 1
      fi
    fi

    # Pre-build OUTSIDE the timed readiness window, under the same exported
    # env the app runs with — the env participates in cargo's fingerprint, so
    # a warm binary can still cost a full thin-LTO relink (measured
    # 2026-08-30: a 180s ceiling died mid-rustc; absorbed here instead).
    if ! cargo build --bin "$APP_NAME" --release > "$DATA_DIR/logs/build.log" 2>&1; then
      echo "boot: cargo build --bin $APP_NAME --release failed" >&2
      echo "  Build log: $DATA_DIR/logs/build.log" >&2
      exit 1
    fi
    # xtask too — the readiness poll runs `cargo xtask harness:ready`, so a
    # stale xtask would otherwise rebuild INSIDE the timed window.
    if ! cargo build -p xtask >> "$DATA_DIR/logs/build.log" 2>&1; then
      echo "boot: cargo build -p xtask failed" >&2
      echo "  Build log: $DATA_DIR/logs/build.log" >&2
      exit 1
    fi

    # Spawn the dev-build binary BY PATH — no cargo wrapper: $! IS the app,
    # and the app itself overwrites the default pidfile with the same
    # identity at boot (pulse-app/src/main.rs::write_pid_file).
    APP_BIN="target/release/$APP_NAME"
    if [ -f "$APP_BIN.exe" ]; then
      APP_BIN="$APP_BIN.exe"
    elif [ ! -f "$APP_BIN" ]; then
      echo "boot: built binary not found at target/release/$APP_NAME[.exe]" >&2
      exit 1
    fi
    # The app runs under a waiting subshell that records how it ended: once
    # boot returns, the app is an orphan nothing else can reap, so a death
    # after `ready` would otherwise leave no status anywhere (harness:status
    # reads this record as `ended`).
    EXIT_FILE="$(dirname "$PIDFILE")/andromeda-pulse.exit"
    SPAWN_FILE="$(dirname "$PIDFILE")/andromeda-pulse.spawn"
    rm -f "$EXIT_FILE" "$SPAWN_FILE"
    if [ "$PROGRAM" = window ]; then
      rm -f "$WITNESS_FILE"
    fi
    (
      # The preload is set on this one command, never exported: the builds
      # above and the verbs after it run without it.
      if [ "$PROGRAM" = console ]; then
        "$APP_BIN" run > "$DATA_DIR/logs/boot.log" 2>&1 &
      elif [ -n "$WITNESS_LIB" ]; then
        LD_PRELOAD="$WITNESS_LIB" ANDROMEDA_PULSE_EXIT_WITNESS_FILE="$WITNESS_FILE" \
          "$APP_BIN" > "$DATA_DIR/logs/boot.log" 2>&1 &
      else
        "$APP_BIN" > "$DATA_DIR/logs/boot.log" 2>&1 &
      fi
      app=$!
      echo "$app" > "$SPAWN_FILE"
      rc=0
      wait "$app" || rc=$?
      if [ "$rc" -gt 128 ]; then
        echo "signal $((rc - 128)) ($(kill -l $((rc - 128)) 2>/dev/null || echo unknown))" > "$EXIT_FILE"
      else
        echo "exit $rc" > "$EXIT_FILE"
      fi
    ) < /dev/null > /dev/null 2>&1 &
    for _ in $(seq 50); do
      [ -s "$SPAWN_FILE" ] && break
      sleep 0.1
    done
    DAEMON_PID=$(tr -d '[:space:]' < "$SPAWN_FILE" 2>/dev/null || true)
    if [ -z "$DAEMON_PID" ]; then
      echo "boot: the app did not start (no spawn record)" >&2
      exit 1
    fi
    echo "$DAEMON_PID" > "$PIDFILE"

    # Poll `cargo xtask harness:ready` — the REAL-process status verdict (PID
    # file + the app's own log-family freshness) AND a TCP handshake on both
    # resolved OTLP ports, so ready is only reported once the spawned app is
    # writing and its receivers accept (test-plan §3 boot, Readiness signal;
    # the status verdict alone read ready before the receivers bound). The
    # verdict is asked for the program just spawned: the boot record that
    # names it is the first one the engine boot writes, so a poll that reads
    # the log a moment early reads wrong-program once and the next one ready.
    last_ready=""
    deadline=$(($(date +%s) + STATUS_TIMEOUT_SEC))
    while [ "$(date +%s)" -lt "$deadline" ]; do
      if last_ready=$(ANDROMEDA_PULSE_PIDFILE="$PIDFILE" ANDROMEDA_PULSE_LOGFILE="$LOGFILE" \
        cargo xtask harness:ready --program "$PROGRAM" 2>/dev/null); then
        echo "boot: ready (PID=$DAEMON_PID, data_dir=$DATA_DIR)"
        echo "  OTLP gRPC:    127.0.0.1:$GRPC_PORT"
        echo "  OTLP HTTP:    127.0.0.1:$HTTP_PORT"
        echo "  Log file:     $LOGFILE"
        exit 0
      fi
      sleep 1
    done
    echo "boot: failed to reach ready state within ${STATUS_TIMEOUT_SEC}s" >&2
    echo "  Boot log: $DATA_DIR/logs/boot.log" >&2
    # Name HOW the app ended when it is already gone: a native crash prints
    # nothing of its own, and a clean exit (every window closed) is silent too.
    # The waiting wrapper writes the record the moment it reaps the app.
    if kill -0 "$DAEMON_PID" 2>/dev/null; then
      echo "  app still running (pid $DAEMON_PID) but never reported healthy" >&2
      case "$last_ready" in
        *'"refusing"'*)
          echo "  the receivers never both accepted: OTLP gRPC 127.0.0.1:$GRPC_PORT, OTLP HTTP 127.0.0.1:$HTTP_PORT" >&2
          ;;
      esac
    else
      for _ in $(seq 20); do
        [ -s "$EXIT_FILE" ] && break
        sleep 0.1
      done
      echo "  app ended: $(cat "$EXIT_FILE" 2>/dev/null || echo 'not recorded')" >&2
    fi
    # Through bash, not as an executable: the checkout's mode bit is not
    # guaranteed (a Windows commit records 100644).
    bash "$0" cleanup
    exit 1
    ;;

  run)
    # Execute cargo-nextest test suite (per-process isolation prevents port-binding conflicts)
    cargo nextest run --workspace --profile ci --message-format libtest-json
    ;;

  status)
    # Real-process verdict about THIS harness's resolved paths: JSON with
    # {verdict, pid, program, log_file_basename, last_write_age_seconds};
    # exit 0 only for running-healthy (pid file present + log family written
    # <= 60s ago) on a run whose log records the program asked for.
    ANDROMEDA_PULSE_DATA_DIR="$DATA_DIR" \
      ANDROMEDA_PULSE_PIDFILE="$PIDFILE" \
      ANDROMEDA_PULSE_LOGFILE="$LOGFILE" \
      cargo xtask harness:status --program "$PROGRAM"
    ;;

  cleanup)
    # Terminate the app by the pidfile identity (the app's own write is
    # canonical; the boot-time $! covers only the crashed-before-write
    # window), then derive the verdict ONLY from independent probes — pid
    # liveness + TCP handshake on the resolved loopback ports — never from
    # the kill's own exit (test-plan §3 cleanup, the measured
    # wrong-reason-pass).
    pid=""
    if [ -f "$PIDFILE" ]; then
      pid=$(tr -d '[:space:]' < "$PIDFILE" 2>/dev/null || true)
    fi

    # Liveness across both pid spaces: msys kill -0 knows shell children;
    # PowerShell knows native Windows pids. The PowerShell branch answers
    # only by genuinely probing — no fallback may manufacture the answer.
    pid_alive() {
      if kill -0 "$1" 2>/dev/null; then return 0; fi
      if command -v powershell.exe >/dev/null 2>&1; then
        powershell.exe -NoProfile -Command "if (Get-Process -Id $1 -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }" >/dev/null 2>&1
        return $?
      fi
      return 1
    }
    terminate_pid() {
      if kill -TERM "$1" 2>/dev/null; then return 0; fi
      if command -v powershell.exe >/dev/null 2>&1; then
        powershell.exe -NoProfile -Command "Stop-Process -Id $1 -ErrorAction SilentlyContinue" >/dev/null 2>&1 || true
      fi
    }
    force_kill_pid() {
      if kill -KILL "$1" 2>/dev/null; then return 0; fi
      if command -v powershell.exe >/dev/null 2>&1; then
        powershell.exe -NoProfile -Command "Stop-Process -Id $1 -Force -ErrorAction SilentlyContinue" >/dev/null 2>&1 || true
      fi
    }

    if [ -n "$pid" ] && pid_alive "$pid"; then
      terminate_pid "$pid"
      # Bounded wait, polling pid liveness each second
      for i in 1 2 3 4 5; do
        if ! pid_alive "$pid"; then
          break
        fi
        sleep 1
      done
      if pid_alive "$pid"; then
        force_kill_pid "$pid"
        sleep 1
      fi
    fi
    if [ -f "$PIDFILE" ]; then
      rm -f "$PIDFILE"
    fi

    # Independent verification: pid liveness + OTLP ports on loopback
    pid_still_alive=0
    if [ -n "$pid" ] && pid_alive "$pid"; then
      pid_still_alive=1
    fi
    ports_accepting=0
    for port in "$GRPC_PORT" "$HTTP_PORT"; do
      if timeout 1 bash -c "cat < /dev/null > /dev/tcp/127.0.0.1/$port" 2>/dev/null; then
        ports_accepting=1
      fi
    done

    verdict="clean"
    if [ "$pid_still_alive" -eq 1 ]; then
      verdict="app-survived"
    elif [ "$ports_accepting" -eq 1 ]; then
      if [ -n "$pid" ]; then
        verdict="ports-lingering"
      else
        verdict="no-pid-ports-accepting"
      fi
    fi

    # Remove tempdir if we created it (only when ANDROMEDA_PULSE_DATA_DIR was unset)
    if [ -z "${ANDROMEDA_PULSE_DATA_DIR_KEEP:-}" ] && [ -d "$DATA_DIR" ] && [[ "$DATA_DIR" == */agent-run-* ]]; then
      rm -rf "$DATA_DIR"
    fi
    echo "cleanup: $verdict"
    if [ "$verdict" = "clean" ]; then
      exit 0
    fi
    exit 1
    ;;

  logs)
    # Tail the structured JSON log family (obs-plan §3 sink path).
    # tracing_appender's daily roller date-suffixes the sink
    # (agent-latest.jsonl.YYYY-MM-DD), so each candidate is a GLOB: a
    # bare-name read finds nothing on a healthy boot and reports an empty log.
    resolved=""
    for base in "$LOGFILE" \
                "$HOME/.andromeda-pulse/logs/agent-latest.jsonl" \
                "$DATA_DIR/logs/agent-latest.jsonl"; do
      # Within one base, the last existing match is the newest: the glob
      # expands in lexical order and the date suffix sorts ascending.
      for candidate in "$base"*; do
        [ -f "$candidate" ] && resolved="$candidate"
      done
      # Earlier bases take precedence, so stop at the first that resolved.
      [ -n "$resolved" ] && break
    done
    if [ -n "$resolved" ]; then
      tail -F "$resolved"
    else
      echo "logs: no log file found at $LOGFILE* or fallback locations" >&2
      exit 1
    fi
    ;;

  *)
    usage
    ;;
esac
