#!/usr/bin/env bash
# scripts/agent-run.sh — agent-driven verification harness driver
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# 5-command discipline:
#   boot     — start pulse-app in background, wait for TauRPC `health` ready (10s timeout)
#   run      — execute cargo-nextest test suite
#   status   — poll TauRPC `health` via cargo xtask harness:status
#   cleanup  — SIGTERM the running pulse-app PID, verify ports released, remove tempdir
#   logs     — tail the structured JSON log file
#
# Bound contracts:
#   - test-plan §3: 5-command discipline, status endpoint shape, PID file path, log format
#   - obs-plan §3: structured log path (~/.andromeda-pulse/logs/agent-latest.jsonl), tracing JSON

set -euo pipefail

# Resolve harness paths (override-friendly via env vars per arch §Occupied Resources)
TMP_BASE="${TMPDIR:-/tmp}"
DATA_DIR="${ANDROMEDA_PULSE_DATA_DIR:-$TMP_BASE/agent-run-$$}"
PIDFILE="${ANDROMEDA_PULSE_PIDFILE:-$DATA_DIR/run/andromeda-pulse.pid}"
LOGFILE="${ANDROMEDA_PULSE_LOGFILE:-$DATA_DIR/logs/agent-latest.jsonl}"
STATUS_TIMEOUT_SEC="${HARNESS_STATUS_TIMEOUT:-10}"
GRPC_PORT="${ANDROMEDA_PULSE_OTLP_GRPC_PORT:-4317}"
HTTP_PORT="${ANDROMEDA_PULSE_OTLP_HTTP_PORT:-4318}"

mkdir -p "$DATA_DIR/run" "$DATA_DIR/logs"

case "${1:-}" in
  boot)
    # Start pulse-app in background with isolated data dir
    export ANDROMEDA_PULSE_DATA_DIR="$DATA_DIR"
    export ANDROMEDA_PULSE_LOG_LEVEL="${ANDROMEDA_PULSE_LOG_LEVEL:-debug}"
    export RUST_LOG="${RUST_LOG:-debug}"

    cargo run --bin pulse-app --release > "$DATA_DIR/logs/boot.log" 2>&1 &
    DAEMON_PID=$!
    echo "$DAEMON_PID" > "$PIDFILE"

    # Poll TauRPC `health` via cargo xtask harness:status (xtask has Tauri test runtime access)
    deadline=$(($(date +%s) + STATUS_TIMEOUT_SEC))
    while [ "$(date +%s)" -lt "$deadline" ]; do
      if cargo xtask harness:status >/dev/null 2>&1; then
        echo "boot: ready (PID=$DAEMON_PID, data_dir=$DATA_DIR)"
        echo "  OTLP gRPC:    127.0.0.1:$GRPC_PORT"
        echo "  OTLP HTTP:    127.0.0.1:$HTTP_PORT"
        echo "  Log file:     $LOGFILE"
        exit 0
      fi
      sleep 1
    done
    echo "boot: failed to reach ready state within ${STATUS_TIMEOUT_SEC}s" >&2
    echo "  Boot log: $DATA_DIR/logs/boot.log" >&2
    "$0" cleanup
    exit 1
    ;;

  run)
    # Execute cargo-nextest test suite (per-process isolation prevents port-binding conflicts)
    cargo nextest run --workspace --profile ci --message-format libtest-json
    ;;

  status)
    # Invoke TauRPC `health` via xtask (xtask uses tauri::test::mock_builder + get_ipc_response)
    # Returns JSON with {status, subsystems, uptime_ms, pid}
    cargo xtask harness:status
    ;;

  cleanup)
    # SIGTERM the running pulse-app, verify ports released, remove tempdir
    if [ -f "$PIDFILE" ]; then
      pid=$(cat "$PIDFILE")
      if kill -0 "$pid" 2>/dev/null; then
        kill -TERM "$pid" 2>/dev/null || true
        # Wait up to 5s for graceful shutdown
        for i in 1 2 3 4 5; do
          if ! kill -0 "$pid" 2>/dev/null; then
            break
          fi
          sleep 1
        done
        # Escalate to SIGKILL if still alive
        if kill -0 "$pid" 2>/dev/null; then
          kill -KILL "$pid" 2>/dev/null || true
        fi
      fi
      rm -f "$PIDFILE"
    fi

    # Verify OTLP ports released (TCP handshake should fail)
    for port in "$GRPC_PORT" "$HTTP_PORT"; do
      if timeout 1 bash -c "cat < /dev/null > /dev/tcp/127.0.0.1/$port" 2>/dev/null; then
        echo "cleanup: warning — port $port still accepting connections" >&2
      fi
    done

    # Remove tempdir if we created it (only when ANDROMEDA_PULSE_DATA_DIR was unset)
    if [ -z "${ANDROMEDA_PULSE_DATA_DIR_KEEP:-}" ] && [ -d "$DATA_DIR" ] && [[ "$DATA_DIR" == */agent-run-* ]]; then
      rm -rf "$DATA_DIR"
    fi
    echo "cleanup: done"
    ;;

  logs)
    # Tail the structured JSON log file (obs-plan §3 sink path)
    if [ -f "$LOGFILE" ]; then
      tail -F "$LOGFILE"
    else
      # Fallback chain
      for candidate in "$HOME/.andromeda-pulse/logs/agent-latest.jsonl" "$DATA_DIR/logs/agent-latest.jsonl"; do
        if [ -f "$candidate" ]; then
          tail -F "$candidate"
          exit 0
        fi
      done
      echo "logs: no log file found at $LOGFILE or fallback locations" >&2
      exit 1
    fi
    ;;

  *)
    echo "Usage: $0 {boot|run|status|cleanup|logs}" >&2
    echo "" >&2
    echo "Bindings:" >&2
    echo "  test-plan §3 — 5-command discipline, status endpoint, PID file" >&2
    echo "  obs-plan §3  — JSON log file at ~/.andromeda-pulse/logs/agent-latest.jsonl" >&2
    exit 2
    ;;
esac
