# scripts/agent-run.ps1 — agent-driven verification harness driver (Windows)
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# 5-command discipline (mirrors agent-run.sh):
#   boot, run, status, cleanup, logs
#
# Run with: .\scripts\agent-run.ps1 boot

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Resolve harness paths (override-friendly via env vars per arch §Occupied Resources)
$DataDir = if ($env:ANDROMEDA_PULSE_DATA_DIR) { $env:ANDROMEDA_PULSE_DATA_DIR } else { Join-Path $env:TEMP "agent-run-$PID" }
$PidFile = if ($env:ANDROMEDA_PULSE_PIDFILE) { $env:ANDROMEDA_PULSE_PIDFILE } else { Join-Path $DataDir "run\andromeda-pulse.pid" }
$LogFile = if ($env:ANDROMEDA_PULSE_LOGFILE) { $env:ANDROMEDA_PULSE_LOGFILE } else { Join-Path $DataDir "logs\agent-latest.jsonl" }
$StatusTimeoutSec = if ($env:HARNESS_STATUS_TIMEOUT) { [int]$env:HARNESS_STATUS_TIMEOUT } else { 10 }
$GrpcPort = if ($env:ANDROMEDA_PULSE_OTLP_GRPC_PORT) { [int]$env:ANDROMEDA_PULSE_OTLP_GRPC_PORT } else { 4317 }
$HttpPort = if ($env:ANDROMEDA_PULSE_OTLP_HTTP_PORT) { [int]$env:ANDROMEDA_PULSE_OTLP_HTTP_PORT } else { 4318 }

if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }
if (-not (Test-Path (Join-Path $DataDir 'run'))) { New-Item -ItemType Directory -Path (Join-Path $DataDir 'run') -Force | Out-Null }
if (-not (Test-Path (Join-Path $DataDir 'logs'))) { New-Item -ItemType Directory -Path (Join-Path $DataDir 'logs') -Force | Out-Null }

function Invoke-Status {
    # Invoke TauRPC `health` via xtask (xtask uses tauri::test::mock_builder + get_ipc_response)
    # Returns JSON with {status, subsystems, uptime_ms, pid}
    & cargo xtask 'harness:status'
    if ($LASTEXITCODE -ne 0) { throw "harness:status returned $LASTEXITCODE" }
}

function Invoke-Cleanup {
    if (Test-Path $PidFile) {
        $procId = Get-Content $PidFile -ErrorAction SilentlyContinue
        if ($procId) {
            $proc = Get-Process -Id $procId -ErrorAction SilentlyContinue
            if ($proc) {
                Stop-Process -Id $procId -ErrorAction SilentlyContinue
                # Wait up to 5s for graceful shutdown
                for ($i = 0; $i -lt 5; $i++) {
                    Start-Sleep -Seconds 1
                    $stillAlive = Get-Process -Id $procId -ErrorAction SilentlyContinue
                    if (-not $stillAlive) { break }
                }
                # Escalate to forced kill if still alive
                $stillAlive = Get-Process -Id $procId -ErrorAction SilentlyContinue
                if ($stillAlive) {
                    Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue
                }
            }
        }
        Remove-Item $PidFile -ErrorAction SilentlyContinue
    }

    # Verify OTLP ports released
    foreach ($port in @($GrpcPort, $HttpPort)) {
        try {
            $tcp = New-Object System.Net.Sockets.TcpClient
            $tcp.SendTimeout = 1000
            $tcp.ReceiveTimeout = 1000
            $async = $tcp.BeginConnect('127.0.0.1', $port, $null, $null)
            $waited = $async.AsyncWaitHandle.WaitOne(1000, $false)
            if ($waited -and $tcp.Connected) {
                Write-Warning "cleanup: port $port still accepting connections"
            }
            $tcp.Close()
        } catch { }
    }

    # Remove tempdir if we created it
    if (-not $env:ANDROMEDA_PULSE_DATA_DIR_KEEP -and ($DataDir -match 'agent-run-')) {
        if (Test-Path $DataDir) {
            Remove-Item $DataDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    Write-Output 'cleanup: done'
}

switch ($args[0]) {
    'boot' {
        $env:ANDROMEDA_PULSE_DATA_DIR = $DataDir
        if (-not $env:ANDROMEDA_PULSE_LOG_LEVEL) { $env:ANDROMEDA_PULSE_LOG_LEVEL = 'debug' }
        if (-not $env:RUST_LOG) { $env:RUST_LOG = 'debug' }

        $bootLog = Join-Path $DataDir 'logs\boot.log'
        $proc = Start-Process -FilePath 'cargo' -ArgumentList 'run','--bin','pulse-app','--release' `
            -RedirectStandardOutput $bootLog -RedirectStandardError $bootLog `
            -PassThru -NoNewWindow
        $proc.Id | Out-File -FilePath $PidFile -Encoding ASCII

        # Poll for ready
        $deadline = (Get-Date).AddSeconds($StatusTimeoutSec)
        while ((Get-Date) -lt $deadline) {
            try {
                Invoke-Status | Out-Null
                Write-Output "boot: ready (PID=$($proc.Id), data_dir=$DataDir)"
                Write-Output "  OTLP gRPC:    127.0.0.1:$GrpcPort"
                Write-Output "  OTLP HTTP:    127.0.0.1:$HttpPort"
                Write-Output "  Log file:     $LogFile"
                exit 0
            } catch {
                Start-Sleep -Seconds 1
            }
        }
        Write-Error "boot: failed to reach ready state within $StatusTimeoutSec`s"
        Write-Output "  Boot log: $bootLog"
        Invoke-Cleanup
        exit 1
    }
    'run' {
        # Execute cargo-nextest test suite
        & cargo nextest run --workspace --profile ci --message-format libtest-json
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    }
    'status' {
        Invoke-Status
    }
    'cleanup' {
        Invoke-Cleanup
    }
    'logs' {
        # Tail the structured JSON log file (obs-plan §3 sink path)
        $candidates = @($LogFile, "$env:USERPROFILE\.andromeda-pulse\logs\agent-latest.jsonl", (Join-Path $DataDir 'logs\agent-latest.jsonl'))
        foreach ($candidate in $candidates) {
            if (Test-Path $candidate) {
                Get-Content $candidate -Wait -Tail 0
                exit 0
            }
        }
        Write-Error "logs: no log file found at $LogFile or fallback locations"
        exit 1
    }
    default {
        Write-Error 'Usage: .\agent-run.ps1 {boot|run|status|cleanup|logs}'
        Write-Output ''
        Write-Output 'Bindings:'
        Write-Output '  test-plan §3 — 5-command discipline, status endpoint, PID file'
        Write-Output '  obs-plan §3  — JSON log file at ~/.andromeda-pulse/logs/agent-latest.jsonl'
        exit 2
    }
}
