# scripts/agent-run.ps1 — agent-driven verification harness driver (Windows)
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# 5-command discipline (mirrors agent-run.sh):
#   boot, run, status, cleanup, logs
#
# Run with: .\scripts\agent-run.ps1 boot

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# UTF-8 relay: without these, Python helpers invoked from the harness decode
# their own output under the host's legacy codepage and mangle non-ASCII.
# The Console pair is the Windows-only half — PowerShell otherwise re-encodes
# child-process output through the OEM codepage before it reaches a pipe.
$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8

# Resolve harness paths (override-friendly via env vars per arch §Occupied Resources)
$DataDir = if ($env:ANDROMEDA_PULSE_DATA_DIR) { $env:ANDROMEDA_PULSE_DATA_DIR } else { Join-Path $env:TEMP "agent-run-$PID" }
$PidFile = if ($env:ANDROMEDA_PULSE_PIDFILE) { $env:ANDROMEDA_PULSE_PIDFILE } else { Join-Path $DataDir "run\andromeda-pulse.pid" }
$LogFile = if ($env:ANDROMEDA_PULSE_LOGFILE) { $env:ANDROMEDA_PULSE_LOGFILE } else { Join-Path $DataDir "logs\agent-latest.jsonl" }
$StatusTimeoutSec = if ($env:HARNESS_STATUS_TIMEOUT) { [int]$env:HARNESS_STATUS_TIMEOUT } else { 10 }
$GrpcPort = if ($env:ANDROMEDA_PULSE_OTLP_GRPC_PORT) { [int]$env:ANDROMEDA_PULSE_OTLP_GRPC_PORT } else { 4317 }
$HttpPort = if ($env:ANDROMEDA_PULSE_OTLP_HTTP_PORT) { [int]$env:ANDROMEDA_PULSE_OTLP_HTTP_PORT } else { 4318 }

if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }
if (-not (Test-Path (Join-Path $DataDir 'run'))) { New-Item -ItemType Directory -Path (Join-Path $DataDir 'run') -Force | Out-Null }
if (-not (Test-Path (Join-Path $DataDir 'logs'))) { New-Item -ItemType Directory -Path (Join-Path $DataDir 'logs') -Force | Out-Null }

function Invoke-Status {
    # Real-process verdict about this harness's resolved paths: JSON with
    # {verdict, pid, log_file_basename, last_write_age_seconds}; exit 0 only
    # for running-healthy (pid file present + log family written <= 60s ago).
    $env:ANDROMEDA_PULSE_DATA_DIR = $DataDir
    $env:ANDROMEDA_PULSE_PIDFILE = $PidFile
    $env:ANDROMEDA_PULSE_LOGFILE = $LogFile
    & cargo xtask 'harness:status'
    if ($LASTEXITCODE -ne 0) { throw "harness:status returned $LASTEXITCODE" }
}

$script:LastReady = ''
function Invoke-Ready {
    # The boot verb's readiness verdict: the status verdict above AND a TCP
    # handshake on both resolved OTLP ports (test-plan §3 boot, Readiness
    # signal). The last verdict is kept so a failed poll can name what it read.
    $env:ANDROMEDA_PULSE_DATA_DIR = $DataDir
    $env:ANDROMEDA_PULSE_PIDFILE = $PidFile
    $env:ANDROMEDA_PULSE_LOGFILE = $LogFile
    $script:LastReady = (& cargo xtask 'harness:ready') -join "`n"
    if ($LASTEXITCODE -ne 0) { throw "harness:ready returned $LASTEXITCODE" }
}

function Invoke-Cleanup {
    # The verdict derives ONLY from independent probes (pid liveness + TCP
    # handshake on the resolved loopback ports), never from the terminate
    # call's own status — test-plan §3 cleanup, the measured wrong-reason-pass.
    $procId = $null
    if (Test-Path $PidFile) {
        $raw = Get-Content $PidFile -ErrorAction SilentlyContinue
        if ($raw) { $procId = "$raw".Trim() }
    }

    if ($procId) {
        $proc = Get-Process -Id $procId -ErrorAction SilentlyContinue
        if ($proc) {
            Stop-Process -Id $procId -ErrorAction SilentlyContinue
            # Bounded wait, polling pid liveness each second
            for ($i = 0; $i -lt 5; $i++) {
                Start-Sleep -Seconds 1
                $stillAlive = Get-Process -Id $procId -ErrorAction SilentlyContinue
                if (-not $stillAlive) { break }
            }
            # Escalate to forced kill if still alive
            $stillAlive = Get-Process -Id $procId -ErrorAction SilentlyContinue
            if ($stillAlive) {
                Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue
                Start-Sleep -Seconds 1
            }
        }
        Remove-Item $PidFile -ErrorAction SilentlyContinue
    }

    # Independent verification: pid liveness + OTLP ports on loopback
    $pidAlive = $false
    if ($procId) {
        if (Get-Process -Id $procId -ErrorAction SilentlyContinue) { $pidAlive = $true }
    }
    $portsAccepting = $false
    foreach ($port in @($GrpcPort, $HttpPort)) {
        try {
            $tcp = New-Object System.Net.Sockets.TcpClient
            $tcp.SendTimeout = 1000
            $tcp.ReceiveTimeout = 1000
            $async = $tcp.BeginConnect('127.0.0.1', $port, $null, $null)
            $waited = $async.AsyncWaitHandle.WaitOne(1000, $false)
            if ($waited -and $tcp.Connected) { $portsAccepting = $true }
            $tcp.Close()
        } catch { }
    }

    $verdict = 'clean'
    if ($pidAlive) { $verdict = 'app-survived' }
    elseif ($portsAccepting) {
        if ($procId) { $verdict = 'ports-lingering' } else { $verdict = 'no-pid-ports-accepting' }
    }

    # Remove tempdir if we created it
    if (-not $env:ANDROMEDA_PULSE_DATA_DIR_KEEP -and ($DataDir -match 'agent-run-')) {
        if (Test-Path $DataDir) {
            Remove-Item $DataDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    Write-Output "cleanup: $verdict"
    if ($verdict -eq 'clean') { $script:CleanupExit = 0 } else { $script:CleanupExit = 1 }
}

switch ($args[0]) {
    'boot' {
        $env:ANDROMEDA_PULSE_DATA_DIR = $DataDir
        if (-not $env:ANDROMEDA_PULSE_LOG_LEVEL) { $env:ANDROMEDA_PULSE_LOG_LEVEL = 'debug' }
        if (-not $env:RUST_LOG) { $env:RUST_LOG = 'debug' }

        # Pre-build OUTSIDE the timed readiness window, under the same exported
        # env the app runs with — the env participates in cargo's fingerprint,
        # so a warm binary can still cost a full thin-LTO relink (measured
        # 2026-08-30: a 180s ceiling died mid-rustc; absorbed here instead).
        $buildLog = Join-Path $DataDir 'logs\build.log'
        $buildErr = Join-Path $DataDir 'logs\build.err.log'
        $build = Start-Process -FilePath 'cargo' -ArgumentList 'build','--bin','pulse-app','--release' `
            -RedirectStandardOutput $buildLog -RedirectStandardError $buildErr `
            -PassThru -NoNewWindow -Wait
        if ($build.ExitCode -ne 0) {
            Write-Warning "boot: cargo build --bin pulse-app --release failed (log: $buildErr)"
            exit 1
        }
        # xtask too — the readiness poll runs `cargo xtask harness:ready`, so
        # a stale xtask would otherwise rebuild INSIDE the timed window.
        $xtaskLog = Join-Path $DataDir 'logs\build-xtask.log'
        $xtaskErr = Join-Path $DataDir 'logs\build-xtask.err.log'
        $buildX = Start-Process -FilePath 'cargo' -ArgumentList 'build','-p','xtask' `
            -RedirectStandardOutput $xtaskLog -RedirectStandardError $xtaskErr `
            -PassThru -NoNewWindow -Wait
        if ($buildX.ExitCode -ne 0) {
            Write-Warning "boot: cargo build -p xtask failed (log: $xtaskErr)"
            exit 1
        }

        # Spawn the release binary BY PATH — no cargo wrapper: the spawn record
        # holds the app's own pid, and the app itself overwrites the default
        # pidfile with the same identity at boot (main.rs::write_pid_file).
        $appBin = Join-Path 'target' (Join-Path 'release' 'pulse-app.exe')
        if (-not (Test-Path $appBin)) {
            Write-Warning "boot: built binary not found at $appBin"
            exit 1
        }
        $bootLog = Join-Path $DataDir 'logs\boot.log'
        $bootErr = Join-Path $DataDir 'logs\boot.err.log'

        # The app runs under a hidden waiting wrapper that records how it ended:
        # once boot returns, nothing else holds the app, so a death after `ready`
        # would otherwise leave no status anywhere (harness:status reads this
        # record as `ended`). Records are one ASCII line with no BOM, the grammar
        # xtask's read_ended accepts.
        $runDir = Split-Path -Parent $PidFile
        $exitFile = Join-Path $runDir 'andromeda-pulse.exit'
        $spawnFile = Join-Path $runDir 'andromeda-pulse.spawn'
        Remove-Item $exitFile, $spawnFile -ErrorAction SilentlyContinue
        $q = { param($s) "'" + ($s -replace "'", "''") + "'" }
        $wrapper = @(
            "`$p = Start-Process -FilePath $(& $q (Resolve-Path $appBin).Path) -RedirectStandardOutput $(& $q $bootLog) -RedirectStandardError $(& $q $bootErr) -PassThru -NoNewWindow",
            '$null = $p.Handle',
            "[System.IO.File]::WriteAllText($(& $q $spawnFile), [string]`$p.Id, [System.Text.Encoding]::ASCII)",
            '$p.WaitForExit()',
            "[System.IO.File]::WriteAllText($(& $q $exitFile), ('exit ' + `$p.ExitCode), [System.Text.Encoding]::ASCII)"
        ) -join "`n"
        $encoded = [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($wrapper))
        Start-Process -FilePath 'powershell' -WindowStyle Hidden `
            -ArgumentList '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-EncodedCommand', $encoded | Out-Null

        $appPid = $null
        for ($i = 0; $i -lt 50; $i++) {
            if (Test-Path $spawnFile) {
                $raw = Get-Content $spawnFile -ErrorAction SilentlyContinue
                if ($raw) { $appPid = "$raw".Trim(); break }
            }
            Start-Sleep -Milliseconds 100
        }
        if (-not $appPid) {
            Write-Output 'boot: the app did not start (no spawn record)'
            exit 1
        }
        [System.IO.File]::WriteAllText($PidFile, $appPid, [System.Text.Encoding]::ASCII)

        # Poll for ready
        $deadline = (Get-Date).AddSeconds($StatusTimeoutSec)
        while ((Get-Date) -lt $deadline) {
            try {
                Invoke-Ready
                Write-Output "boot: ready (PID=$appPid, data_dir=$DataDir)"
                Write-Output "  OTLP gRPC:    127.0.0.1:$GrpcPort"
                Write-Output "  OTLP HTTP:    127.0.0.1:$HttpPort"
                Write-Output "  Log file:     $LogFile"
                exit 0
            } catch {
                Start-Sleep -Seconds 1
            }
        }
        Write-Warning "boot: failed to reach ready state within $StatusTimeoutSec`s (boot log: $bootLog)"
        # Name HOW the app ended when it is already gone: a native crash prints
        # nothing of its own, and a clean exit is silent too.
        if (Get-Process -Id $appPid -ErrorAction SilentlyContinue) {
            Write-Output "  app still running (pid $appPid) but never reported healthy"
            if ($script:LastReady -match '"refusing"') {
                Write-Output "  the receivers never both accepted: OTLP gRPC 127.0.0.1:$GrpcPort, OTLP HTTP 127.0.0.1:$HttpPort"
            }
        } else {
            for ($i = 0; $i -lt 20; $i++) {
                if (Test-Path $exitFile) { break }
                Start-Sleep -Milliseconds 100
            }
            $ended = if (Test-Path $exitFile) { (Get-Content $exitFile -ErrorAction SilentlyContinue) } else { 'not recorded' }
            Write-Output "  app ended: $ended"
        }
        Invoke-Cleanup
        exit 1
    }
    'run' {
        # Execute cargo-nextest test suite
        & cargo nextest run --workspace --profile ci --message-format libtest-json
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    }
    'status' {
        Invoke-Status
    }
    'cleanup' {
        Invoke-Cleanup
        exit $script:CleanupExit
    }
    'logs' {
        # Tail the structured JSON log file (obs-plan §3 sink path)
        $candidates = @($LogFile, "$env:USERPROFILE\.andromeda-pulse\logs\agent-latest.jsonl", (Join-Path $DataDir 'logs\agent-latest.jsonl'))
        foreach ($candidate in $candidates) {
            if (Test-Path $candidate) {
                Get-Content $candidate -Wait -Tail 0
                exit 0
            }
        }
        Write-Error "logs: no log file found at $LogFile or fallback locations"
        exit 1
    }
    default {
        Write-Error 'Usage: .\agent-run.ps1 {boot|run|status|cleanup|logs}'
        Write-Output ''
        Write-Output 'Bindings:'
        Write-Output '  test-plan §3 — 5-command discipline, status endpoint, PID file'
        Write-Output '  obs-plan §3  — JSON log file at ~/.andromeda-pulse/logs/agent-latest.jsonl'
        exit 2
    }
}
