// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type AppError = { kind: "validation"; field: string; reason: string } | { kind: "not_found"; resource: string } | { kind: "internal"; message: string } | { kind: "plugin"; plugin_id: string; message: string } | { kind: "storage"; message: string } | { kind: "ingest"; message: string }

export type AppInfo = { name: string; version: string; rust_version: string; tauri_version: string; features: string[]; build_profile: string }

/**
 * 5-state connection lifecycle FSM. `#[serde(tag = "state")]` discriminator
 * gives the TauRPC TypeScript binding a discriminated union the compiler
 * enforces exhaustive `switch` on — preserves a11y SC 1.4.1 not-color-alone
 * affordance at the wire boundary (per a11y plan §6 + plan.md §A11y row).
 */
export type ConnectionState = { state: "Listening" } | { state: "Receiving" } | { state: "Idle" } | { state: "Stalled" } | { state: "ReceiverFailed" }

/**
 * Wire payload for the `pulse://stream/connection-state` broadcast topic
 * AND the `connection.current_state` TauRPC procedure response. Carries
 * only semantic state + lag + sanitized reason — NO presentation fields
 * (`displayColor` / `iconGlyph` / `cssClass` are forbidden per design
 * plan extract).
 */
export type ConnectionStatePayload = { state: ConnectionState; last_span_ago_ms: number; severity: Severity; message: string | null; reason: ReceiverFailureReason | null }

/**
 * Kind of detected condition emitted as an attention cue. Bounded
 * enumeration; future kinds are added explicitly (no `Other(String)`
 * catch-all). Variants serialize as snake_case strings. Chunk #78 added
 * the `Hash` derive (needed for `IncidentRegistry` cool-down map keying)
 * AND the cfg-gated `specta::Type` derive (for cross-bridge type
 * generation via `IncidentLifecycleEvent`).
 */
export type CueKind = "error_rate_spike" | "latency_regression" | "restart_event" | "service_went_silent" | "retry_storm"

/**
 * Scope an attention cue applies to: a single service, a single operation
 * within a service, or the global pipeline. Bounded enumeration; variants
 * serialize as snake_case strings. Chunk #78 added `Hash` derive +
 * cfg-gated `specta::Type` derive (parallel к `CueKind`).
 */
export type CueScope = "service" | "operation" | "global"

export type DriftIndicatorPayload = "Healthy" | "OverGeneralized" | "UnderClustered"

/**
 * One `(dimension, label) -> count` entry in the preview summary. `Vec` of
 * these (rather than a map) keeps the TS binding shape stable across specta
 * releases. `dimension` is `"status"` or `"severity"`.
 */
export type ExportCategoryCount = { dimension: string; label: string; count: number }

/**
 * Pre-write preview summary surfaced across the TauRPC bridge. `written`
 * is false on the preview-only path (no file written); true after the
 * confirmed write. `categories` aggregates counts by `status` + `severity`.
 */
export type ExportPreviewPayload = { categories: ExportCategoryCount[]; total_records: number; date_range_start_unix_nano: number | null; date_range_end_unix_nano: number | null; anonymization_confirmed: boolean; written: boolean; written_path_basename: string | null }

export type FrameDurationInput = { duration_ms: number; wgpu_backend: WgpuBackend; webview_backend: WebviewBackend; timing_method: TimingMethod }

export type HealthEnvelope = { status: HealthStatus; checked_at: string; subsystems: SubsystemStatuses; pid: number; uptime_ms: number }

export type HealthStatus = "ok" | "degraded"

/**
 * Single ranked hypothesis. Mirrors `interpretation::markdown::HypothesisView`
 * but с specta::Type derive for cross-bridge transport (interpretation
 * crate has no taurpc/specta dep per arch §Module dependency direction).
 */
export type HypothesisPayload = { statement: string; confidence_label: string; justification: string }

/**
 * Resolver-facing view of an Incident. Narrower than the full `triage::
 * contract::Incident` struct — drops raw `evidence_refs` byte arrays
 * (downstream UI displays the `evidence_count` instead) AND drops the
 * fingerprint string (internal grouping identifier; not user-relevant).
 * Webview consumers receive this shape over the TauRPC bridge.
 */
export type IncidentRecord = { id: number; workspace: string; kind: CueKind; scope: CueScope; status: IncidentStatus; severity: IncidentSeverity; priority_tier: PriorityTier; title: string; detail: string; opened_at_unix_nano: number; updated_at_unix_nano: number; acknowledged_at_unix_nano: number | null; resolved_at_unix_nano: number | null; read_at_unix_nano: number | null; evidence_count: number }

/**
 * Severity level for an incident. Bounded enumeration; mirrors
 * `tracing::Level` ordering for future event integration. Variants
 * serialize as snake_case strings. Chunk #78 added cfg-gated
 * `specta::Type` derive (for cross-bridge `IncidentRecord` resolver
 * envelope). The TypeScript binding is renamed `IncidentSeverity`
 * к disambiguate from `ingest::connection::Severity` (same identifier,
 * distinct domain — connection severity vs incident severity); specta
 * rejects duplicate type names across the bindings.ts emission.
 */
export type IncidentSeverity = "info" | "warn" | "error" | "critical"

/**
 * Lifecycle state of an incident per capability spec P-022 auto-resolution
 * flow. Active = currently surfaced; Acknowledged = user acknowledged but
 * underlying signal still active; Resolved = signal has not re-emitted for
 * the cool-down window (120s default). Chunk #78 added cfg-gated
 * `specta::Type` derive (for cross-bridge type generation via
 * `IncidentLifecycleEvent` payload + `IncidentRecord` resolver envelope).
 */
export type IncidentStatus = "active" | "acknowledged" | "resolved"

/**
 * Paginated list envelope per arch §Standard Contracts. `next_cursor`
 * reserved для future pagination wire-up; chunk #78 returns the full
 * active-incident set in one response (bounded by 120s auto-resolution
 * + 10-min recent-history display window).
 */
export type IncidentsListPayload = { items: IncidentRecord[]; total: number; next_cursor: string | null }

/**
 * Single suggested investigation step с expected yield description.
 */
export type InvestigationStepPayload = { step: string; expected_yield: string }

export type LogRow = { ts_unix_nano: number; resource_hash: string; severity_number: number; body: string; severity_text: string; trace_id: string; span_id: string }

export type LogsQueryArgs = { time_window_seconds: number; limit: number; cursor: string | null }

export type MarkAllReadPayload = { affected_count: number; marked_at_unix_nano: number }

export type McpServerState = "enabled" | "disabled" | "unavailable"

export type McpStartResult = { state: McpServerState; pid: number | null }

export type McpStatusDto = { state: McpServerState; sidecar_running: boolean; pid: number | null; 
/**
 * Connected-agent identity (chunk #94). The main process knows the
 * sidecar is running (Child handle) but not whether an MCP agent has
 * connected to its stdio peer; at this chunk's scope this is the
 * sidecar-running state surfaced as a bounded label
 * (`Some("stdio-client")` when running, else `None`). The "Send to
 * agent" button in the Diagnostic Report toolbar gates on
 * `Settings.mcp_server_enabled AND connected_agent.is_some()`.
 */
connected_agent: string | null }

export type McpStopResult = { state: McpServerState }

export type MetricRow = { metric_name: string; ts_unix_nano: number; resource_hash: string; value: number; data_point_kind: number }

export type MetricsQueryArgs = { time_window_seconds: number; limit: number; cursor: string | null }

/**
 * Payload returned by `model.current_profile`. All fields are String /
 * Option<String> к sidestep cross-crate specta derive plumbing — the
 * strings are bounded snake_case labels (validated by the upstream
 * enum-to-label fns); webview consumers get string types in their
 * TypeScript bindings + assert against the same bounded set.
 */
export type ModelProfilePayload = { 
/**
 * Bounded snake_case label: `unknown` / `gpu_primary` / `gpu_fallback`
 * / `cpu_primary` / `cpu_fallback`.
 */
profile_label: string; 
/**
 * Bounded snake_case label: `primary` / `fallback`.
 */
tier_label: string; 
/**
 * Bounded snake_case label: `loading` / `loaded` / `error`.
 */
load_status: string; 
/**
 * Semantic name (e.g., `"llama-3.2-3b-instruct-q4_k_m"`); `None`
 * when the model is not loaded (Loading or Error state).
 * NEVER а file path or checkpoint URL per security extract.
 */
model_identity_name: string | null }

export type PaginatedResponse<T> = { items: T[]; total: number; next_cursor: string | null }

export type PluginDto = { id: string; basename: string; category: string; byte_count: number }

export type PluginInvokeResult = { plugin_id: string; capability: string; allowed: boolean }

export type PluginListEnvelope = { items: PluginDto[]; total: number; next_cursor: string | null }

export type PresetPromptDto = { id: string; label: string }

/**
 * Cross-incident "Previously seen" match per P-036. Chunk #88 reserves
 * the field shape; current resolver always returns empty Vec (corpus
 * fingerprint-similarity query path is а follow-up chunk).
 */
export type PreviouslySeenPayload = { incident_id: number; opened_at_unix_nano: number; title: string; workspace: string }

/**
 * Three-tier severity model per capability spec P-019. Autonomous = model
 * is highly confident (surfaces with prominent halo shift and counter
 * increment); Suggested = model believes likely problem with reservations
 * (quiet counter increment, minimal halo); Curious = worth recording for
 * pattern learning, no interruption (Findings dropdown collapsed section).
 * Chunk #78 added cfg-gated `specta::Type` derive (for cross-bridge
 * `IncidentRecord` resolver envelope).
 */
export type PriorityTier = "autonomous" | "suggested" | "curious"

export type ReadyChecks = { duckdb_connection: string; ingest_mpsc_capacity_pct: number; broadcast_subscribers: number; plugins_loaded: number; mcp_server_enabled: boolean }

export type ReadyEnvelope = { ready: boolean; checked_at: string; checks: ReadyChecks }

/**
 * Closed-enum failure reason. Carries NO file-path / line-number /
 * library-version / Rust-struct-name content — satisfies security plan
 * §Anti-Patterns §Logging row 1 + a11y plan §8 plain-language commitment.
 */
export type ReceiverFailureReason = "bind_failed" | "stale_heartbeat" | "receiver_panicked"

/**
 * Six-section Report payload returned by `incidents.get_report(id)`
 * (chunk #88 — Epoch 9 Foundation v0.2.0). Carries structured fields
 * for the in-app webview surface AND а pre-serialized `markdown` string
 * for the Copy markdown action (P-038 byte-identical к future MCP
 * delivery #92 per project doc §87 contract).
 * 
 * Hybrid render contract (chunk #88 Phase 1 user-approved scope):
 * - `degraded_mode = false` indicates Resolved incident с parsed L4Output
 * payload — full six-section content.
 * - `degraded_mode = true` indicates Active/Acknowledged incident OR
 * Resolved incident с unparseable / redacted resolution_summary_text —
 * hypotheses + investigation_steps replaced by explicit "interpretation
 * pending" notice in the markdown OR webview.
 */
export type ReportPayload = { incident_id: number; title: string; workspace: string; opened_at_unix_nano: number; status: IncidentStatus; severity: IncidentSeverity; symptom: string; timeline: string; hypotheses: HypothesisPayload[]; investigation_steps: InvestigationStepPayload[]; evidence_refs: string[]; project_context: string; degraded_mode: boolean; resolution_summary: string | null; previously_seen: PreviouslySeenPayload[]; markdown: string }

/**
 * Chunk #86 — Settings → Diagnostics "Retry interpretation now" payload.
 * Returned by `diagnostics.retry_interpretation()` after invoking the
 * manual-override path on the degraded-mode FSM.
 * 
 * Bounded к scalar / string-label fields per chunk #86 obs constraint
 * aggregate-only discipline; carries NO LLM-emitted content / incident
 * identifiers / per-trace IDs. The `current_state` label is the snake-
 * case bounded enum from `interpretation::degraded_mode::DegradedModeState`
 * ("active" | "degraded") routed through `degraded_mode_state_label`.
 */
export type RetryInterpretationPayload = { 
/**
 * True if the manual-retry invocation transitioned FSM state OR
 * reset а live failure counter; false if FSM was already в clean
 * Active state с zero consecutive failures (no-op retry).
 */
triggered: boolean; 
/**
 * Post-invocation FSM state label ("active" | "degraded").
 */
current_state: string; consecutive_failures: number; backoff_remaining_seconds: number }

/**
 * Per-service lifecycle state per capability spec P-027. Seven discrete
 * states ordered roughly by activity intensity (most-active first;
 * Archived = effectively-removed end state). The `Unknown` variant exists
 * for services seen via prior corpus but not yet observed in the current
 * session (chunk #69 corpus restore territory).
 */
export type ServiceLifecycleState = "unknown" | "bootstrapping" | "active" | "quiet" | "silent" | "dormant" | "archived"

/**
 * Item returned by `ServiceRegistry::list_all` for the
 * `services.list_with_states` TauRPC resolver. Service name is bounded
 * telemetry identifier; manual_override is the operator pin (None when
 * natural state).
 */
export type ServiceListItem = { service: string; state: ServiceLifecycleState; last_seen_unix_nano: number; manual_override: ServiceLifecycleState | null; 
/**
 * Max priority tier across active service-scoped incidents attributed to
 * this service (`None` when no active incident). The registry holds no
 * incident data, so `list_all` always emits `None`; the
 * `services.list_with_states` resolver enriches this by joining the
 * incident registry on `scope_id`. Drives the constellation dot hue.
 */
priority_tier?: PriorityTier | null }

/**
 * Paginated list envelope per arch §Standard Contracts. `next_cursor`
 * reserved for future pagination wire-up; chunk #67 returns the full set
 * in one response (registry is bounded by `ACTIVITY_FLOOR_SERVICE_CAP`).
 */
export type ServiceListPayload = { items: ServiceListItem[]; total: number; next_cursor: string | null }

export type Settings = { theme?: Theme; widget_position?: WidgetPosition; retention_seconds?: number; mcp_server_enabled?: boolean; notifications_enabled?: boolean; always_on_top?: boolean; snapshot_preset?: SnapshotPreset; snapshot_format?: SnapshotFormat; lifecycle_dormant_after_secs?: number; lifecycle_archived_after_secs?: number; drain_depth?: number; drain_similarity_x100?: number; drain_max_clusters?: number; cadence_baseline_seconds?: number; cadence_accelerated_seconds?: number; cadence_reflection_seconds?: number; cadence_tier2_acceleration_enabled?: boolean }

/**
 * Severity hint enabling future webview `aria-live` polite-vs-assertive
 * selection without re-deriving severity from state-enum string matching
 * (per a11y plan §7 Live regions table).
 */
export type Severity = "info" | "warning" | "critical"

export type SnapshotFormat = "markdown" | "json"

export type SnapshotPreset = "conservative" | "balanced" | "detailed"

export type SnapshotResultDto = { token_count: number; markdown_path_basename: string; json_path_basename: string; preset_prompts: PresetPromptDto[]; byte_count: number; dedup_count: number }

/**
 * Per-table record counts + on-disk byte size + schema version. Cross-bridge
 * envelope for the `storage.inspect` resolver.
 */
export type StorageInspectPayload = { record_counts: TableRecordCount[]; total_bytes_on_disk: number; schema_version: number }

/**
 * Corpus DB filesystem path + size + schema version envelope. Path is
 * the canonicalized string surfaced across the bridge; the matching
 * `tracing` event in `storage.path.request` emits basename only per
 * obs-plan §1 Vector 6.
 */
export type StoragePathPayload = { path: string; size_bytes: number; schema_version: number }

export type SubsystemStatus = { status: string; error_msg: string | null; last_tick_at: string | null }

export type SubsystemStatuses = { otlp_grpc_receiver: SubsystemStatus; otlp_http_receiver: SubsystemStatus; buffer: SubsystemStatus; ingest_channel: SubsystemStatus; viz: SubsystemStatus; plugins: SubsystemStatus }

/**
 * Single table → record count entry. Vec<TableRecordCount> in the
 * payload (rather than a map) keeps the TS binding shape stable
 * across specta releases.
 */
export type TableRecordCount = { table: string; count: number }

export type TemplateDistEntryPayload = { id: number; content: string; occurrence_count: number; drift_indicator: DriftIndicatorPayload }

export type TemplateDistributionPayload = { templates: TemplateDistEntryPayload[]; total_template_count: number; last_updated_unix_nano: number }

export type Theme = "dark" | "light" | "auto"

export type TimingMethod = "cpu" | "gpu"

export type TraceRow = { trace_id: string; span_id: string; ts_unix_nano: number; service: string; duration_ms: number; error_count: number }

export type TracesQueryArgs = { time_window_seconds: number; limit: number; cursor: string | null }

export type WebviewBackend = "webview2" | "wkwebview" | "gtkwebkit"

export type WgpuBackend = "vulkan" | "metal" | "dx12"

export type WidgetPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right"

export type WorkspaceContextDto = { root_basename: string; project_name: string | null; vcs_type: string | null; vcs_root_basename: string | null; has_andromeda_marker: boolean }

const ARGS_MAP = { '':'{"app_info":[],"get_settings":[],"health":[],"ready":[],"update_settings":["settings"]}', 'connection':'{"current_state":[]}', 'diagnostics':'{"retry_interpretation":[],"template_distribution":[]}', 'incidents':'{"acknowledge":["id"],"get_report":["id"],"list_active":[],"mark_all_read":[],"mark_resolved":["id"]}', 'logs':'{"query":["args"]}', 'mcp':'{"start":[],"status":[],"stop":[]}', 'metrics':'{"query":["args"]}', 'model':'{"current_profile":[]}', 'plugins':'{"invoke":["plugin_id","capability"],"list":[],"reload":[]}', 'services':'{"list_with_states":[]}', 'snapshot':'{"generate":["preset","workspace_root"]}', 'storage':'{"export_for_training":["target_path","confirm"],"inspect":[],"path":[]}', 'streams':'{"subscribe_logs":["channel"],"subscribe_metrics":["channel"],"subscribe_spans":["channel"]}', 'telemetry.frontend':'{"record_frame_ms":["input"]}', 'traces':'{"query":["args"]}', 'workspace':'{"detect":["candidate_root"]}' }
export type Router = { "": {app_info: () => Promise<AppInfo>, 
get_settings: () => Promise<Settings>, 
health: () => Promise<HealthEnvelope>, 
ready: () => Promise<ReadyEnvelope>, 
update_settings: (settings: Settings) => Promise<null>},
"connection": {current_state: () => Promise<ConnectionStatePayload>},
"diagnostics": {retry_interpretation: () => Promise<RetryInterpretationPayload>, 
template_distribution: () => Promise<TemplateDistributionPayload>},
"incidents": {acknowledge: (id: number) => Promise<null>, 
get_report: (id: number) => Promise<ReportPayload>, 
list_active: () => Promise<IncidentsListPayload>, 
mark_all_read: () => Promise<MarkAllReadPayload>, 
mark_resolved: (id: number) => Promise<null>},
"logs": {query: (args: LogsQueryArgs) => Promise<PaginatedResponse<LogRow>>},
"mcp": {start: () => Promise<McpStartResult>, 
status: () => Promise<McpStatusDto>, 
stop: () => Promise<McpStopResult>},
"metrics": {query: (args: MetricsQueryArgs) => Promise<PaginatedResponse<MetricRow>>},
"model": {current_profile: () => Promise<ModelProfilePayload>},
"plugins": {invoke: (pluginId: string, capability: string) => Promise<PluginInvokeResult>, 
list: () => Promise<PluginListEnvelope>, 
reload: () => Promise<PluginListEnvelope>},
"services": {list_with_states: () => Promise<ServiceListPayload>},
"snapshot": {generate: (preset: SnapshotPreset, workspaceRoot: string | null) => Promise<SnapshotResultDto>},
"storage": {export_for_training: (targetPath: string | null, confirm: boolean) => Promise<ExportPreviewPayload>, 
inspect: () => Promise<StorageInspectPayload>, 
path: () => Promise<StoragePathPayload>},
"streams": {subscribe_logs: (channel: TAURI_CHANNEL<number[]>) => Promise<null>, 
subscribe_metrics: (channel: TAURI_CHANNEL<number[]>) => Promise<null>, 
subscribe_spans: (channel: TAURI_CHANNEL<number[]>) => Promise<null>},
"telemetry.frontend": {record_frame_ms: (input: FrameDurationInput) => Promise<null>},
"traces": {query: (args: TracesQueryArgs) => Promise<PaginatedResponse<TraceRow>>},
"workspace": {detect: (candidateRoot: string) => Promise<WorkspaceContextDto>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
